# -*- coding: utf-8 -*-
"""
renogybt.datamodels
~~~~~~~~~~~~~~~~~~~

This module defines dataclasses used to represent structured data retrieved from
Renogy devices. These dataclasses provide type hinting and a clear structure
for device-specific information, replacing generic dictionaries for improved
code clarity and maintainability.

Each device type (e.g., Rover, Battery) typically has its own dataclass that
inherits from `BaseDeviceData`, which contains common fields like model and
device ID (read from the device).
"""
from dataclasses import dataclass, field
from typing import Optional, Dict

# The typing.List import was removed by ruff as it was unused.
# If it's needed for future dataclasses, it should be re-added.


@dataclass
class BaseDeviceData:
    """
    Base dataclass for common device information.

    This class is intended to be subclassed by device-specific dataclasses.
    It includes fields that are generally available from most Renogy devices,
    such as the model string and the device ID read from the hardware.

    Attributes:
        model: The device model string, e.g., "RNG-CTRL-RVR40".
               Populated by `BaseClient._parse_device_info`.
        device_id: The Modbus ID of the device, as read from the device itself.
                   This might differ from the ID specified in the configuration.
                   Populated by `BaseClient._parse_device_address`.
        function: The function code of the MODBUS response (e.g., "READ", "WRITE").
                  This is often populated by client-specific parsers.
                  Note: Metadata fields `__device` (alias from config) and
                  `__client` (client class name) are added by `BaseClient`
                  before the data object is passed to the callback and are
                  not defined as explicit fields here.
    """

    model: Optional[str] = None
    device_id: Optional[int] = None
    function: Optional[str] = None


@dataclass
class RoverData(BaseDeviceData):
    """
    Dataclass for Renogy Rover solar charge controller data.

    This includes real-time operational data such as battery parameters,
    PV (solar panel) input, load output, and daily/total statistics.

    Attributes:
        battery_percentage: State of Charge (SOC) of the battery (%).
        battery_voltage: Current battery voltage (V).
        battery_current: Current flowing into/out of the battery (A).
                         Positive for charging, negative for discharging.
        battery_temperature: Temperature of the battery sensor (°C or °F).
        controller_temperature: Internal temperature of the charge controller (°C or °F).
        load_status: Whether the load output is 'on' or 'off'.
        load_voltage: Voltage at the load terminals (V).
        load_current: Current drawn by the load (A).
        load_power: Power consumed by the load (W).
        pv_voltage: Voltage from the solar panels (V).
        pv_current: Current from the solar panels (A).
        pv_power: Power generated by the solar panels (W).
        max_charging_power_today: Maximum charging power recorded today (W).
        max_discharging_power_today: Maximum discharging power recorded today (W) (if applicable).
        charging_amp_hours_today: Accumulated charging amp-hours today (Ah).
        discharging_amp_hours_today: Accumulated discharging amp-hours today (Ah).
        power_generation_today: Total power generated today (kWh or Wh - unit depends on device).
        power_consumption_today: Total power consumed by load today (kWh or Wh).
        power_generation_total: Cumulative power generated (kWh or Wh).
        charging_status: Current charging state (e.g., 'mppt', 'boost', 'floating').
        battery_type: Configured battery type (e.g., 'open', 'sealed', 'lithium').
    """

    # From parse_chargin_info
    battery_percentage: Optional[int] = None
    battery_voltage: Optional[float] = None
    battery_current: Optional[float] = None
    battery_temperature: Optional[float] = None
    controller_temperature: Optional[float] = None
    load_status: Optional[str] = None
    load_voltage: Optional[float] = None
    load_current: Optional[float] = None
    load_power: Optional[int] = None
    pv_voltage: Optional[float] = None
    pv_current: Optional[float] = None
    pv_power: Optional[int] = None
    max_charging_power_today: Optional[int] = None
    max_discharging_power_today: Optional[int] = None
    charging_amp_hours_today: Optional[int] = None
    discharging_amp_hours_today: Optional[int] = None
    power_generation_today: Optional[int] = None
    power_consumption_today: Optional[int] = None
    power_generation_total: Optional[int] = None
    charging_status: Optional[str] = None

    # From parse_battery_type
    battery_type: Optional[str] = None
    # Note: `function` is inherited from BaseDeviceData.
    # RoverClient's parse_set_load_response returns a simple dict, not part of RoverData.


@dataclass
class BatteryData(BaseDeviceData):
    """
    Dataclass for Renogy smart battery data.

    Includes information about individual cell voltages, temperatures, overall battery
    parameters like current, voltage, and state of charge.

    Attributes:
        cell_count: Number of battery cells.
        cell_voltages: Dictionary mapping cell index (int) to cell voltage (float, V).
                       e.g., `{0: 3.30, 1: 3.31, ...}`
        sensor_count: Number of temperature sensors in the battery.
        temperatures: Dictionary mapping sensor index (int) to temperature (float, °C or °F).
                      e.g., `{0: 25.0, 1: 25.5, ...}`
        current: Overall battery current (A). Positive for charging, negative for discharging.
        voltage: Overall battery terminal voltage (V).
        remaining_charge: Estimated remaining charge in Amp-hours (Ah).
        capacity: Nominal or configured battery capacity in Amp-hours (Ah).
    """

    # From parse_cell_volt_info
    cell_count: Optional[int] = None
    cell_voltages: Dict[int, float] = field(default_factory=dict)

    # From parse_cell_temp_info
    sensor_count: Optional[int] = None
    temperatures: Dict[int, float] = field(default_factory=dict)

    # From parse_battery_info
    current: Optional[float] = None
    voltage: Optional[float] = None
    remaining_charge: Optional[float] = None
    capacity: Optional[float] = None
    # Note: `function`, `model`, `device_id` are inherited from BaseDeviceData.


# TODO: Add dataclasses for InverterClient, DCChargerClient, RoverHistoryClient
#       if they are brought into the new dataclass-based system.
#       This would involve identifying their specific data fields from their parsers.
